name: AKS Workflow Template

on:
  workflow_call:
    inputs:
      componente:
        description: "Nombre del componente a construir"
        type: object
        required: true
    secrets:
      gh_token:
        description: "GitHub Token para autenticación"
        required: true

jobs:
  template-build:
    uses: ./.github/workflows/workflow-aks-build.yaml
    with:
      componente: ${{ inputs.componente }}
    secrets:
      gh_token: ${{ secrets.gh_token }}

  template-deploy:
    uses: ./.github/workflows/workflow-aks-deploy.yaml
    needs: template-build
    with:
      componente: ${{ inputs.componente }}
    secrets:
      gh_token: ${{ secrets.gh_token }}

  template-validator:
    uses: ./.github/workflows/workflow-aks-validator.yaml
    needs: template-deploy
    with:
      componente: ${{ inputs.componente }}
    secrets:
      gh_token: ${{ secrets.gh_token }}