name: AKS Workflow Template

on:
  workflow_call:
    inputs:
      nombre:
        description: 'Nombre del microservicio'
        required: true
        type: string
      namespace:
        description: 'Namespace de Kubernetes'
        required: true
        type: string
      aks:
        description: 'Nombre del cluster AKS'
        required: true
        type: string
      squad:
        description: 'Nombre del squad'
        required: true
        type: string
      repoValidation:
        description: 'Repositorio de validaciones'
        required: true
        type: string
        default: ''
      folderValidation:
        description: 'Carpeta de validaciones'
        required: true
        type: string
        default: ''
      smokeFile:
        description: 'Nombre del archivo de pruebas de humo'
        required: true
        type: string
        default: 'smoke_test.postman_collection.json'
      acceptanceFile:
        description: 'Nombre del archivo de pruebas de aceptación'
        required: true
        type: string
        default: 'acceptance_test.postman_collection.json'
      noAG:
        description: 'Indica si no se utiliza API Gateway'
        required: true
        type: boolean
        default: false
      servicePort:
        description: 'Puerto del servicio'
        required: true
        type: string
        default: '8080'
      certificate_hv:
        description: 'Certificado HV'
        required: false
        type: string
        default: null
      certificate_ag:
        description: 'Certificado AG'
        required: false
        type: string
        default: null
      certificate_ca:
        description: 'Certificado CA'
        required: false
        type: string
        default: null
    secrets:
      gh_token:
        description: "GitHub Token para autenticación"
        required: true

jobs:
  template-build:
    uses: ./.github/workflows/workflow-aks-build.yaml
    with:
      nombre: ${{ inputs.nombre }}
      namespace: ${{ inputs.namespace }}
      aks: ${{ inputs.aks }}
      squad: ${{ inputs.squad }}
      repoValidation: ${{ inputs.repoValidation }}
      folderValidation: ${{ inputs.folderValidation }}
      smokeFile: ${{ inputs.smokeFile }}
      acceptanceFile: ${{ inputs.acceptanceFile }}
      noAG: ${{ inputs.noAG }}
      servicePort: ${{ inputs.servicePort }}
      certificate_hv: ${{ inputs.certificate_hv }}
      certificate_ag: ${{ inputs.certificate_ag }}
      certificate_ca: ${{ inputs.certificate_ca }}
    secrets:
      gh_token: ${{ secrets.gh_token }}

  template-deploy:
    uses: ./.github/workflows/workflow-aks-deploy.yaml
    needs: template-build
    with:
      nombre: ${{ inputs.nombre }}
      namespace: ${{ inputs.namespace }}
      aks: ${{ inputs.aks }}
      squad: ${{ inputs.squad }}
      repoValidation: ${{ inputs.repoValidation }}
      folderValidation: ${{ inputs.folderValidation }}
      smokeFile: ${{ inputs.smokeFile }}
      acceptanceFile: ${{ inputs.acceptanceFile }}
      noAG: ${{ inputs.noAG }}
      servicePort: ${{ inputs.servicePort }}
      certificate_hv: ${{ inputs.certificate_hv }}
      certificate_ag: ${{ inputs.certificate_ag }}
      certificate_ca: ${{ inputs.certificate_ca }}
    secrets:
      gh_token: ${{ secrets.gh_token }}

  template-validator:
    uses: ./.github/workflows/workflow-aks-validator.yaml
    needs: template-deploy
    with:
      nombre: ${{ inputs.nombre }}
      namespace: ${{ inputs.namespace }}
      aks: ${{ inputs.aks }}
      squad: ${{ inputs.squad }}
      repoValidation: ${{ inputs.repoValidation }}
      folderValidation: ${{ inputs.folderValidation }}
      smokeFile: ${{ inputs.smokeFile }}
      acceptanceFile: ${{ inputs.acceptanceFile }}
      noAG: ${{ inputs.noAG }}
      servicePort: ${{ inputs.servicePort }}
      certificate_hv: ${{ inputs.certificate_hv }}
      certificate_ag: ${{ inputs.certificate_ag }}
      certificate_ca: ${{ inputs.certificate_ca }}
    secrets:
      gh_token: ${{ secrets.gh_token }}