name: AKS Workflow Template

on:
  workflow_call:
    inputs:
      componente:
        description: "Nombre del componente a construir"
        type: string
        required: true
      token:
        description: "Token de acceso al repositorio"
        type: secret
        required: true


jobs:
  build:
    uses: ./.github/workflows/workflow-aks-build.yaml
    with:
      componente: ${{ inputs.componente }}
      token: ${{ inputs.token }}

  deploy:
    uses: ./.github/workflows/workflow-aks-deploy.yaml
    needs: build
    with:
      componente: ${{ inputs.componente }}

  validate:
    uses: ./.github/workflows/workflow-aks-validator.yaml
    needs: deploy
    with:
      componente: ${{ inputs.componente }}