name: Reusable AKS validator Workflow

on:
  workflow_call:
    inputs:
      nombre:
        description: 'Nombre del microservicio'
        required: true
        type: string
      namespace:
        description: 'Namespace de Kubernetes'
        required: true
        type: string
      aks:
        description: 'Nombre del cluster AKS'
        required: true
        type: string
      squad:
        description: 'Nombre del squad'
        required: true
        type: string
      repoValidation:
        description: 'Repositorio de validaciones'
        required: true
        type: string
        default: ''
      folderValidation:
        description: 'Carpeta de validaciones'
        required: true
        type: string
        default: ''
      smokeFile:
        description: 'Nombre del archivo de pruebas de humo'
        required: true
        type: string
        default: 'smoke_test.postman_collection.json'
      acceptanceFile:
        description: 'Nombre del archivo de pruebas de aceptación'
        required: true
        type: string
        default: 'acceptance_test.postman_collection.json'
      noAG:
        description: 'Indica si no se utiliza API Gateway'
        required: true
        type: boolean
        default: false
      servicePort:
        description: 'Puerto del servicio'
        required: true
        type: string
        default: '8080'
      certificate_hv:
        description: 'Certificado HV'
        required: false
        type: string
        default: null
      certificate_ag:
        description: 'Certificado AG'
        required: false
        type: string
        default: null
      certificate_ca:
        description: 'Certificado CA'
        required: false
        type: string
        default: null
    secrets:
      gh_token:
        description: "GitHub Token para autenticación"
        required: true

jobs:
  validator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Checkout Repository (DevSecOps-scripts)
        uses: actions/checkout@v3
        with:
          repository: test-craizy/DevSecOps-scripts
          token: ${{ secrets.gh_token }}
          path: devsecops-scripts  
          ref: main
          fetch-depth: 0
          
      # - name: run validator
      #   run: chmod +x devsecops-scripts/scripts/aks/validator/validator.sh && devsecops-scripts/scripts/validator/aks/validator/validator.sh
