name: Reusable AKS validator Workflow

on:
  workflow_call:
    inputs:
      componente:
        description: "Nombre del componente a construir"
        type: string
        required: true

jobs:
  validator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Process
        run: ./scripts/validator/validator.sh ${{ inputs.componente }}
