name: AKS Workflow Template

on:
  workflow_call:
    inputs:
      componente:
        description: "Nombre del componente a construir"
        type: string
        required: true
    secrets:
      gh_token:
        description: "GitHub Token para autenticación"
        required: true

jobs:
  build:
    uses: ./.github/workflows/workflow-aks-build.yaml
    with:
      componente: ${{ inputs.componente }}
    secrets:
      gh_token: ${{ secrets.gh_token }}

  deploy:
    uses: ./.github/workflows/workflow-aks-deploy.yaml
    needs: build
    with:
      componente: ${{ inputs.componente }}

  validate:
    uses: ./.github/workflows/workflow-aks-validator.yaml
    needs: deploy
    with:
      componente: ${{ inputs.componente }}