name: AKS Workflow Template

on:
  workflow_call:
    inputs:
      componente:
        description: "Nombre del componente a construir"
        type: string
        required: true
    secrets:
      gh_token:
        description: "GitHub Token para autenticación"
        required: true

jobs:
  build:
    uses: test-craizy/DevSecOps-scripts/.github/workflows/workflow-aks-build.yml@main
    with:
      componente: ${{ inputs.componente }}
    secrets:
      gh_token: ${{ secrets.gh_token }}

  deploy:
    uses: test-craizy/DevSecOps-scripts/.github/workflows/workflow-aks-deploy.yml@main
    needs: build
    with:
      componente: ${{ inputs.componente }}
    # secrets:
    #   gh_token: ${{ secrets.gh_token }}

  validate:
    uses: test-craizy/DevSecOps-scripts/.github/workflows/workflow-aks-validator.yml@main
    needs: deploy
    with:
      componente: ${{ inputs.componente }}
    # secrets:
    #   gh_token: ${{ secrets.gh_token }}